### ISSUE TITLE
"Access to path 'D:\SuperBMD\TexTex\gnd_textex' is denied." Error

### ISSUE THREAD

**Issue by KekMcGee** [Sage-of-Mirrors/SuperBMD#1]
Trying to convert bmd models from Super Mario Sunshine gives me the error above https://i.imgur.com/3Wbko02.png

**Comment by Sage-of-Mirrors** [comment]
I apologize, that was an error. I've fixed it in the code and the next release will not have it.

Thank you for bringing it to my attention! That's what you get when you hardcode filepaths.
