### ISSUE TITLE
Taking .szp (from Luigi's Mansion) into BMD Format

### ISSUE THREAD

**Issue by C112358** [Sage-of-Mirrors/SuperBMD#15]
Hello, 

I'd like some help converting models from Luigi's Mansion (.szp format) into BMD (for later use with Autodesk Maya). I tried running the following command:
`SuperBMD.exe -i C:\Users\[user account]\Desktop\SuperBMD_v1.2\map7.szp -o C:\Users\[user account]\Desktop\SuperBMD_v1.2\ `
but this did not work and resulted in this error:
`Unhandled Exception: System.IO.FileNotFoundException: Filename was null or could not be found
at Assimp.AssimpContext.ImportFile(String file, PostProcessSteps postProcessFlags)
at SuperBMD.Model.Load(String filePath)
at SuperBMD_UnitTest.Program.Main(String[] args)
`
Thank you for your help. I have been working on a large project, and converting these models is one of the last steps I must complete. 

Best, 
C112358

**Comment by ecumber** [comment]
Luigi's Mansion only uses the BMD format in some situations - it isn't the main model format. Also, SZP files are archives, so they have files inside of them, they are not models themselves. You can extract them with a tool called Lunaboy RARC Tools, or if you prefer, Toolbox Reborn (https://github.com/KillzXGaming/Toolbox.Reborn). Another thing to note is that editing the model files (.mdl) is difficult. You can convert them with Toolbox Reborn, but putting them back in the game requires lots of technical knowhow. If you need help with this, you can join the Luigi's Mansion modding discord at https://discord.gg/UjXHz8F.

**Comment by Github3010** [comment]
What does the file extension .szp stand for, in Luigi's Mansion?

**Comment by Sage-of-Mirrors** [comment]
SZP is just an extension indicating the the file is compressed with Nintendo's SZP compression algorithm. I believe in Luigi's Mansion all *.szp files are compressed *.arc files.

**Comment by Github3010** [comment]
Was it Seven Zip Portable compression?

**Comment by Github3010** [comment]
Sage-of-Mirrors, did you answer my last question yet?

**Comment by Github3010** [comment]
Sage-of-Mirrors, did you answer my last question yet? It has been about a year now.

**Comment by ecumber** [comment]
> Was it Seven Zip Portable compression?

SZPs do not use 7zip compression, they use a custom codec named yay0. As such, you will need special tools (see my previous reply) to decompress and extract them.

**Comment by Github3010** [comment]
But what is the real abbreviation, ecumber?

**Comment by Github3010** [comment]
Well, it has been two days. Ecumber, I think the real abbreviation for SZP is Seven Zipped Project file. Am I right?

**Comment by Github3010** [comment]
Ecumber, do you think the real abbreviation for SZP is Seven Zipped Project? Just look at my last post.

**Comment by Sage-of-Mirrors** [comment]
We don't know what SZP stands for. Drop it.

**Comment by Github3010** [comment]
Okay, this is completed, guys.

**Comment by Github3010** [comment]
Thanks for completing this issue!

**Comment by Github3010** [comment]
Actually, it has been nearly a year and I figured out what the compressor was - Seven Zipped Project.
