### ISSUE TITLE
Blender UV problem

### ISSUE THREAD

**Issue by MCMANIRX** [Sage-of-Mirrors/SuperBMD#2]
I tried to import various .blend files with the program, but every time i tried to import a file with at least 1 UV map, there would be an error that said:
![image](https://user-images.githubusercontent.com/24947776/34805893-46343838-f64e-11e7-95d6-3d50e1fb570a.png)
what do?

**Comment by Sage-of-Mirrors** [comment]
Hm. Let's see.

That's an error with AssImp itself. [There's an open issue on it already.](https://github.com/assimp/assimp/issues/325) Unfortunately, this isn't something I can fix. What I would suggest is exporting your .blend files to either .fbx or .dae, then using SuperBMD on those files. If the problem still persists, please feel free to create another issue!
