### ISSUE TITLE
No .exe file

### ISSUE THREAD

**Issue by zoeyorly** [Sage-of-Mirrors/SuperBMD#6]
when I downloaded this program I read the README and it said "drag it onto the executable or run the program via command line: `SuperBMD.exe <model path>" But there was no .exe file present just a bunch of Visual Studio files which couldn't be opened. Did I do something wrong or what?

**Comment by Sage-of-Mirrors** [comment]
You need to download SuperBMD.zip from this page: https://github.com/Sage-of-Mirrors/SuperBMD/releases/tag/v1.1.1
